services:
  pingvin-share:
    build: .
    # image: stonith404/pingvin-share  # original upstream image
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - TRUST_PROXY=true
    volumes:
      - "./data:/opt/app/backend/data"
      - "./data/images:/opt/app/frontend/public/img"
  #      - "./config.yaml:/opt/app/config.yaml" # Add this line, if you want to configure pingvin-share via config file and not via UI
